const CATEGORIAS=new Set(['platinum','gold','silver']);
function autorizado(request,env){const esperado=String(env.ADMIN_TOKEN||'');return esperado&&(request.headers.get('Authorization')||'')===`Bearer ${esperado}`}
function negar(){return Response.json({error:'Acesso administrativo não autorizado.'},{status:401,headers:{'Cache-Control':'no-store'}})}
async function listar(env){const itens=[];let cursor;do{const p=await env.MANTENEDORES.list({prefix:'mantenedor:',cursor,limit:1000});for(const k of p.keys){const r=await env.MANTENEDORES.get(k.name,'json');if(r)itens.push(r)}cursor=p.list_complete?undefined:p.cursor}while(cursor);const peso={platinum:0,gold:1,silver:2};itens.sort((a,b)=>(peso[a.category]??9)-(peso[b.category]??9)||Number(b.amount)-Number(a.amount)||String(a.name).localeCompare(String(b.name)));return itens}
function limpar(b,id){const name=String(b.name||'').trim().slice(0,120),message=String(b.message||'').trim().slice(0,1000),image=String(b.image||'');const amount=Number(b.amount);const category=String(b.category||'').toLowerCase();if(!name||!image||!Number.isFinite(amount)||amount<0||!CATEGORIAS.has(category))throw new Error('Dados do mantenedor inválidos.');return{id,name,message,image,amount,category,active:b.active!==false,updatedAt:new Date().toISOString()}}
export async function onRequestGet({request,env}){if(!autorizado(request,env))return negar();if(!env.MANTENEDORES)return Response.json({error:'Binding MANTENEDORES não configurado.'},{status:500});return Response.json({mantenedores:await listar(env)},{headers:{'Cache-Control':'no-store'}})}
export async function onRequestPost({request,env}){if(!autorizado(request,env))return negar();if(!env.MANTENEDORES)return Response.json({error:'Binding MANTENEDORES não configurado.'},{status:500});try{const b=await request.json(),id=crypto.randomUUID(),r={...limpar(b,id),createdAt:new Date().toISOString()};await env.MANTENEDORES.put(`mantenedor:${id}`,JSON.stringify(r));return Response.json({ok:true,id})}catch(e){return Response.json({error:e.message},{status:400})}}
export async function onRequestPut({request,env}){if(!autorizado(request,env))return negar();try{const b=await request.json();if(!b.id)return Response.json({error:'ID ausente.'},{status:400});const key=`mantenedor:${b.id}`,old=await env.MANTENEDORES.get(key,'json');if(!old)return Response.json({error:'Mantenedor não encontrado.'},{status:404});const r={...limpar(b,b.id),createdAt:old.createdAt||new Date().toISOString()};await env.MANTENEDORES.put(key,JSON.stringify(r));return Response.json({ok:true})}catch(e){return Response.json({error:e.message},{status:400})}}
export async function onRequestDelete({request,env}){if(!autorizado(request,env))return negar();const b=await request.json();if(!b.id)return Response.json({error:'ID ausente.'},{status:400});await env.MANTENEDORES.delete(`mantenedor:${b.id}`);return Response.json({ok:true})}
